### ISSUE TITLE
Quasar linux_arm error: Invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by joaopdelboni** [scakemyer/plugin.video.quasar#225] opened 2016-02-16 22:37 UTC
Hello, I am having problems using the quasar with raspberry, where the application will list movies the daemon generates an exception with the following message: 'invalid memory address or nil pointer dereference'. I'm using rasberry pi and the problem started today, I believe that with the release of version 0.9.18 however, tried to reinstall the version 0.9.17 and the problem continued.

Here the daemon output:

INFO  main         ▶ main             
INFO  main         ▶ main             ________
INFO  main         ▶ main             \_____  \  __ _______    ___________ _______
INFO  main         ▶ main              /  / \  \|  |  \__  \  /  ___/\__  \\_  __ \
INFO  main         ▶ main             /   \_/.  \  |  // __ \_\___ \  / __ \|  | \/
INFO  main         ▶ main             \_____\ \_/____/(____  /____  >(____  /__|
INFO  main         ▶ main                    \__>          \/     \/      \/
INFO  main         ▶ main             
INFO  main         ▶ main             Version: "v0.9.18" Go: go1.6rc2
INFO  config       ▶ Reload           Reloading configuration...
INFO  main         ▶ main             Addon: plugin.video.quasar v0.9.18
INFO  btservice    ▶ configure        Setting Session settings...
INFO  btservice    ▶ configure        Setting Encryption settings...
INFO  btservice    ▶ alertsConsumer   Consuming alerts...
INFO  main         ▶ main             Updating Kodi Addon Repositories
INFO  repository   ▶ GetAddonFiles    Request for: addons.xml.md5
WARN  repository   ▶ getLastRelease   Unable to find a last tag, using master.
WARN  repository   ▶ getLastRelease   Unable to find a last tag, using master.
INFO  repository   ▶ fetchChangelog   Fetching add-on changelog...
[GIN] 2016/02/16 - 20:26:52 | 200 |  3.130842314s | 127.0.0.1 |   GET     /repository/scakemyer/plugin.video.quasar/addons.xml.md5
[GIN] 2016/02/16 - 20:27:04 | 200 |   19.868002ms | 127.0.0.1 |   GET     /movies/
[GIN] 2016/02/16 - 20:27:16 | 200 |   11.901001ms | 127.0.0.1 |   GET     /movies/
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x356edc]

goroutine 75 [running]:
github.com/scakemyer/quasar/tmdb.ListMoviesComplete.func1(0x56fd46d0, 0x56fd6920, 0xae7178, 0xe, 0x56fa0e60, 0x14, 0x14, 0x0, 0x0)
	/go/src/github.com/scakemyer/quasar/tmdb/movie.go:210 +0x248
created by github.com/scakemyer/quasar/tmdb.ListMoviesComplete
	/go/src/github.com/scakemyer/quasar/tmdb/movie.go:213 +0x184

Congratulations to all for the great work, the addon is amazing.

**Comment by scakemyer** [comment] 2016-02-16 23:10
Duplicate of #226

**Closed by scakemyer** 2016-02-16 23:10 UTC
