### ISSUE TITLE
It plays the sample file and not the actual video.

### ISSUE THREAD

**Issue by gkarav** [scakemyer/plugin.video.quasar#778] opened 2017-03-02 02:10 UTC
Quasar + Burst (Latest version)

Sometimes when you select a torrent file although it displays the correct file size upon selecting it chooses to play the uncompressed sample file.

I have noticed that in the cases that i have examined the actual video is compressed and the sample file is uncompressed.

If i remember correctly in most of the cases the issue occurred when selecting a torrent from Torrentleech.

**Comment by scakemyer** [comment] 2017-03-02 02:17
Duplicate of #613, and yes, if the sample file isn't in a rar archive, but the whole video is, there's simply no way we can stream from that, at all. So the best we'll be able to do in #613 is to notify the user that Quasar can't play that particular torrent, stop the download altogether, clean up, which will also prevent crashes when actually trying to play a rar file.

**Closed by scakemyer** 2017-03-02 02:17 UTC

**Comment by gkarav** [comment] 2017-03-02 02:33
Since i have selected not show results less that 250mb for both movies and series in quasar & burst it would be helpful that the specific torrent that is compressed is not shown at all.

**Comment by scakemyer** [comment] 2017-03-02 02:35
That can't be done either, since there's no way to know prior to starting the download, or at least receiving metadata for it, if it's composed of multiple < 250MB files.

**Comment by gkarav** [comment] 2017-03-02 02:47
I am sure you know best but for example in Torrentleech particularly most of data is in compressed in rar and splitted in mulltiple 48mb files.

In that case that actually there i no single file larger that 50mb maybe something can be done.

Please forgive me if i sound stupid, i don’t know the way that you fetch torrent info and what that info contains.

Kind regards

**Comment by scakemyer** [comment] 2017-03-02 02:50
I just explained to you what we can and cannot do, and why. That's all there is to it. I understand the issue very well, and again, the best we can do is explained above.
