### ISSUE TITLE
Episodes are not being marked as watched

### ISSUE THREAD

**Issue by KillerJoeBR** [scakemyer/plugin.video.quasar#821] opened 2017-04-04 04:25 UTC
Hi there, 

In the latest update episodes in the library are not being marked as watched. It doesn't work in the widget panel and it also doesn't work inside the library section (and this was working before).

Movies are working fine even in the widget menu. So it seems to only affects episodes status.

I can provide a log latter, but i'm pretty sure it's a global issue.

Thanks

**Comment by elgatito** [comment] 2017-04-04 04:49
Starting episode from Kodi?
Any episode not marked as watched? Or you open episode, kodi moves to the next, you stop and previous not marked as finished?

**Comment by KillerJoeBR** [comment] 2017-04-04 05:06
Kodi Home menu --> TV Series --> TWD --> Season 7 --> episode 16 

After watching the whole episode, it goes back to season 7 episodes menu and it doesn't get marked as watched.  (this was working in the 0.9.75 version)

The same thing  happens when in the Kodi Home menu i select the episode in the widget panel. (this wasn't working before the 0.9.76 version either but it does work for movies widget menu now)

**Comment by KillerJoeBR** [comment] 2017-04-04 05:07
Usually i watch one episode at a time

**Comment by herrwusel** [comment] 2017-04-04 05:44
No, I'm experiencing this as well since the last update. Later I can provide a log if needed

**Comment by elgatito** [comment] 2017-04-04 05:48
Logs are welcome

**Comment by elgatito** [comment] 2017-04-04 06:02
Tried with automatic jump-to-next-file, tried without. Could not reproduce this. 
Logs needed.

**Comment by elgatito** [comment] 2017-04-04 06:35
Btw, is your scraper in Kodi for shows TMDB?

**Comment by scakemyer** [comment] 2017-04-04 12:06
@elgatito this has nothing to do with jump-to-next or whatever, just a simple regression in 0.9.75

Logs might help, but I have an idea what change might cause this for episodes only.

**Comment by KillerJoeBR** [comment] 2017-04-04 13:39
I can only upload a log tonight cause I am at work right now.

**Comment by elgatito** [comment] 2017-04-04 14:57
What about scraper used for parsing of Quasar library directory?

**Comment by KillerJoeBR** [comment] 2017-04-05 11:31
Ok so here is the log:

http://paste.ubuntu.com/24319796/

**Comment by KillerJoeBR** [comment] 2017-04-05 11:32
i use tvdb scrapper

**Comment by Magic815** [comment] 2017-04-06 02:25
So I've been having the same issue with TV shows not marking as watched anymore - however, I could've sworn that I've been having the problem prior to V0.9.76 hitting, so I didn't necessarily think it was Quasar related. Is anyone able to tell if Quasar might have a hand in my shows not marking as watched anymore?

http://paste.ubuntu.com/24324929/

**Comment by KillerJoeBR** [comment] 2017-04-06 02:45
It was working before (since 0.9.70 i think) But only inside the tv show section, it didn't work while using the next episode widget or any widget in the home menu screen.

**Comment by Magic815** [comment] 2017-04-06 03:19
Well so I know that marking as watched has worked just fine for me when selecting episodes through the 'next episode' widget for the past 6+ months. (Of which while I've had Quasar installed for the past 3 months). It wasn't until about ~1-2 weeks ago where I realized that marking as watched was no longer working through the widget.

So either it's Quasar related and happened recently, or it's not Quasar related at all. Can you see anything in my above logs that would indicate one way or another?

**Comment by scakemyer** [comment] 2017-04-06 03:22
Guys, this was marked as a regression and I referenced the PR that'll have it fixed in the next release.

**Closed** 2017-04-06 15:03 UTC
Labels: regression
