### ISSUE TITLE
library integration issues- how to troubleshoot?

### ISSUE THREAD

**Issue by ElMouse** [scakemyer/plugin.video.quasar#755] opened 2017-02-22 07:50 UTC
Good day. I am having hard time figuring out how exactly Quasar library integration works.

## Expected Behavior
Library integration works correctly.

## Current Behavior
Issues:
1# for some shows (recent example - Last Week tonight with John Oliver) There is this weird behavior. The episodes list from inside Quasar shows list of episode correctly. I have added the show to my library, however only episodes up until season 3 were added to my library (end of 2016) The show is currently 2 episodes into season 4. I can watch it perfectly from inside quasar shows listing, but have hard time figuring out why the recent episodes are not added to my library.
- i have other shows set up and they seem not to have the same problem - new episodes are being added to my library when they come out.
- The example with  Last Week tonight with John Oliver - is the recent one. I have noticed same behavior with other shows before (have been using quasar for 3 years now)

2# Sometimes (this happens not for all shows) The new show is being added to the library before it has been aired (the option to add unaired episodes in quasar is not set) It is being added usually around 12 hours before the episode is actually aired. (Might this be because i am -12 hours from USA? Can i workaroudn that somehow ) usually it is also added without the screenshot and other details. and stays the same afterwards.

## Context
Missing the episodes, mess in library with unaired episodes.

## Your Environment
Version used:
Kodi 16):
Windows 10

Thanks a lot! Quasar is a wonderful piece of software.

**Comment by scakemyer** [comment] 2017-03-31 19:07
Marking as duplicate of #806 which you also filed, can't make heads or tails of this one here... don't mix two issues in one, that's the best way to make sure I won't fix either ;)

**Closed by scakemyer** 2017-03-31 19:07 UTC
