### ISSUE TITLE
Quasar not mark movies or shows watched with trakt

### ISSUE THREAD

**Issue by Jezze83** [scakemyer/plugin.video.quasar#623] opened 2017-01-08 00:10 UTC
When i install quasar for new computer and i successfully authorize trakt from quasar settings, it wont mark as watched any tv shows or movies to quasar? Is that feature what quasar dont have? It mark as watched to trakt when i watch something. Salts addon marking as watched to kodi when authorizing trakt and would be great if quasar do that. I dont have any logs for that because it wont give any logs for it. Another problem is, when i choose something from quasar, example from tv shows and some category its very, very slow. Sometimes i need wait about six minutes before it opens. Anyone else faced this kinda problem?

**Comment by scakemyer** [comment] 2017-01-08 01:04
Duplicate of #518, scheduled for v1.0, please search existing issues before posting. As for Trakt listings being slow, that was also explained in #599.

**Closed by scakemyer** 2017-01-08 01:04 UTC
