### ISSUE TITLE
Request: explicit notification when a provider is ignored because it is too slow. 

### ISSUE THREAD

**Issue by mancuniancol** [scakemyer/plugin.video.quasar#159] opened 2016-02-11 10:07 UTC
It is possible to add a notification in the UI to advice to reduce the number of providers or increase the time out when a provider is ignored because it is too slow. 
I am getting a lot of reports that providers are not working properly and it is a problem of configuration. Too many providers or too low time out. 

I will really appreciate, because I lose a lot of time with that and I am missing the real issues :p

Thanks in advance

**Comment by zorg1977** [comment] 2016-02-11 11:36
Is it possible to set a default timeout value = function (platform) or something like that.
For instance 4 seconds for a RPi 2 is not enough.

**Comment by mancuniancol** [comment] 2016-02-11 12:18
THat is already done.  For Rpi2 is 30 or 40s.  My request is different. I am not asking to change the defaults.

**Comment by mancuniancol** [comment] 2016-02-11 12:25
Then, be polite and create your own request.  Because, you are not asking the same.

**Comment by scakemyer** [comment] 2016-02-11 17:03
Issue hijacking to its finest ;) Yet, this is a duplicate of #141 which will include at least such a notification.

**Closed by scakemyer** 2016-02-11 17:03 UTC

**Comment by mancuniancol** [comment] 2016-02-11 17:08
OK, sorry. My bad. Thank you for your time :)

**Comment by scakemyer** [comment] 2016-02-11 17:26
No worries :)
