### ISSUE TITLE
No Daemon Started message

### ISSUE THREAD

**Issue by KillerJoeBR** [scakemyer/plugin.video.quasar#144] opened 2016-02-10 17:56 UTC
I don't know if this is on purpose but in the latest version i'm not getting the Quasar Daemon Started message anymore. The plugin still open/work but no message. I changed the version back to 0.9.9 and the message displays normally again.

http://pastebin.com/hnjrxUCK (same log as the http 500 error)

**Comment by ShlomiD83** [comment] 2016-02-10 17:59
which language are you using?

**Comment by KillerJoeBR** [comment] 2016-02-10 18:05
portuguese (brazil)

**Comment by ShlomiD83** [comment] 2016-02-10 18:08
having the same problem with hebrew for the last versions, but if i delete the hebrew translation from the languages folder i can see the notifications again, try that with the portuguese folder, until this is fixed.

**Comment by KillerJoeBR** [comment] 2016-02-10 18:23
Yeah i can confirm that everything works fine while using English.

The issue is even bigger cause while using portuguese (brazil) the streams selection window doesn't work either. But it works fine using english language.

**Comment by ShlomiD83** [comment] 2016-02-10 18:27
same here with hebrew, allready opened an issue about the stream selection window.

**Comment by scakemyer** [comment] 2016-02-10 22:16
Duplicate of #142

**Closed by scakemyer** 2016-02-10 22:16 UTC
