### ISSUE TITLE
Enhancement: Show Next page in stream results

### ISSUE THREAD

**Issue by elgatito** [scakemyer/plugin.video.quasar#726] opened 2017-02-14 12:03 UTC
Currrently providers return results, they are sorted by Quasar and limited number it returned to user. 
If user wants to see "next" results - it's impossible.
If user fires up the same search - providers run it once again.

Would be nice to:
1) Store unified results from providers, and cache it for some time.
2) Give ability to see next page of results, that will not bother providers and will be quick enough only to fetch stream files.
3) Cache downloaded stream contents for some time (list of files to be stored).

As long as most relevant results come over first page, then first page default limit can be decreased to speed-up a bit.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Kodi 15/16/17, SPMC, OSMC, OpenELEC):
* Operating System and version (Android 4/5/6, Windows 7/8/10, macOS 10.11, Ubuntu 16.10):
* Link to Kodi debug log:
<!--- See http://kodi.wiki/view/Log_file/Easy or paste to http://paste.ubuntu.com directly

**Comment by scakemyer** [comment] 2017-02-14 12:09
There are no "next" results, no limited number of results, and we wouldn't gain anything either since providers would run the same search whether they'd return a single page or more of results, hence why there is no such thing. Caching of results is a duplicate of #449 already scheduled for v1.0.

**Closed by scakemyer** 2017-02-14 12:09 UTC
