### ISSUE TITLE
Is this project dead??

### ISSUE THREAD

**Issue by ghost** [scakemyer/plugin.video.quasar#887] opened 2017-09-01 14:59 UTC
Seems very quiet around this project and quasar burst. is this dead?

**Comment by Kelso76** [comment] 2017-09-02 13:11
It might be since there is no more update since may and scakemyer hasn't answered anyone in months

**Comment by tomtomclub** [comment] 2017-09-05 15:58
no way. scakenmyer  may  keep little bit Holiday

**Comment by Kelso76** [comment] 2017-09-06 14:59
Of course maybe. But strange he haven't be anywhere here since may.
Nope nothing wrong happened to him

**Comment by vomitous** [comment] 2017-09-18 03:12
Dead? No, it still functuons.  Abandoned?  I doubt it.  Developer busy?  Seems likely

😯

**Comment by aprades** [comment] 2017-09-19 16:07
If this is dead, does anyone know of an alternative as good as this?

**Comment by syneox** [comment] 2017-09-22 13:25
there's one more fork from elgatito here: https://github.com/elgatito/plugin.video.quasar/releases

I have tried it and it's promising but it is also lacking continuous development unfortunately.

**Comment by Znuff** [comment] 2017-09-26 21:59
I've tried that fork on my Android box. It was pretty much unusable. 

It started downloading, filling up the buffer at 8-9MB/sec, but after that, the last 1% the speed dropped at 800KB/s. After that, the download-proper was crawling at 1MB/sec, while the status kept saying "Checking..." then switching to "Downloading..." then back to "Checking...".

**Comment by burekas7** [comment] 2017-10-02 16:02
@scakemyer is the best developer, none of these forks will reach to his work and support.
I'm hoping that he's just taking a break for a while and will return soon for fixing bugs and add new features to this great addon ever.

There are some persons here like @charly3pins that can help him with their support.
But we still need that @scakemyer will be back here.

**Comment by Pibox2** [comment] 2017-10-03 00:46
Thank you syneox. Works fine on PC

**Comment by bam80** [comment] 2017-10-14 19:07
>there's one more fork from elgatito here: https://github.com/elgatito/plugin.video.quasar/releases
I have tried it and it's promising but it is also lacking continuous development unfortunately.

https://github.com/elgatito/plugin.video.quasar
>This branch is even with scakemyer:master. 

Which means there maybe was no additional development

**Comment by elgatito** [comment] 2017-10-17 12:36
> Which means there maybe was no additional development

It means only that there were no changes in Python part, committed to master. 
Python part is responsible for Kodi API calls and localization. 

> I have tried it and it's promising but it is also lacking continuous development unfortunately.

That one will not get more changes, and is considered to be a draft for migrating to anacrolix/torrent from libtorrent. That should, in theory, make possible to compile Quasar for any platform that support Go compiler (like OSX/iOS). Maybe I will ever make a separate fork with renaming and so on.

I have not heard of a fully-working Quasar forks.

**Comment by tomektarnowski** [comment] 2017-11-01 15:01
@elgatito hi m8! Just noticed your fork and it seems at the end that you won't drop elementum for new project, right? :)

**Comment by elgatito** [comment] 2017-11-01 16:23
Elementum  is a hard fork of Quasar. No way back. I will try to make it usable, but no estimates yet...

**Comment by tomektarnowski** [comment] 2017-11-01 17:31
@elgatito what do you mean by usable? I have already seen first version released today - is it hard alfa and you don't recommend to install it? Also, can you somehow open such discussion board under your fork?

**Comment by elgatito** [comment] 2017-11-01 17:40
@unster , v0.0.1 is an early alpha in current state, so worth trying so far.

There is the gitter chat fo Elementum, and issue tracker as well.

**Comment by tomektarnowski** [comment] 2017-11-02 08:01
@elgatito can you please share a link, for some strange reason I can't find issue tracker on elementum page.

**Comment by elgatito** [comment] 2017-11-02 08:13
@unster , sorry, you were right. Somehow Issues were disabled. Now active there - https://github.com/elgatito/plugin.video.elementum/issues

**Comment by pbeeler** [comment] 2017-11-07 07:07
Last commit 7 months ago not good.  I wouldn't really call that a break, more like a extended leave of absence.  And I'm still using this add-on, but I fear it will become completely unsable at some point in the future...

**Comment by KillerJoeBR** [comment] 2017-11-07 12:13
Great to know that here is a new fork being developed. I almost have no free time recently (i'm a dad now) so it's hard to try and test new things. But i keep an eye at this project and new ones. Can yuou say what is the main issue with your new fork right now? Speed? crashes? just curious.

And i would like to wish you good luck

**Comment by elgatito** [comment] 2017-11-07 17:28
> Can yuou say what is the main issue with your new fork right now? Speed? crashes? just curious.

Currently I'm rewriting memory storage for torrents. When used as original Quasar (writing to files) - works fine, in general.

**Comment by burekas7** [comment] 2018-01-16 13:39
@elgatito 

Hi, I have installed your fork yesterday and already found a little regression with some elements, but in general, it seems that you start to do a good work in the Settings there.

My question is do you going to take this fork seriously?
Because I want to start to raise this problems and in additional to ask for enhancments that were opened for quasar and haven't done yet.

Thanks man.

**Comment by elgatito** [comment] 2018-01-16 13:42
@burekas7 , there is a separate repository https://github.com/elgatito/plugin.video.elementum chat and issues tracker for my fork of Quasar. This place should be used for Quasar discussions. Thanks.

**Comment by burekas7** [comment] 2018-01-16 13:46
@elgatito 
I know, of course.
Just asking to know if to start opening my issues there.
Ok then, so I will start soon.
Thanks for you work.

**Comment by aaccioly** [comment] 2018-11-23 18:16
It is now over one year since this issue was first raised. The funny thing is, I was just praising the virtues of Quasar and pointing out how impressed I was with it. I was also pointing out that support for Fibers is a major selling point for Kotlin itself. It is a pity that the project seems to be dead.

Anyway, I just want to point people towards Project Loom: https://openjdk.java.net/projects/loom/ . It may, one day, provide the right foundations for what Quasar was trying to achieve.

**Comment by Znuff** [comment] 2018-11-23 21:38
Look 3 messages above. Someone made a fork and it's actively being worked on.

Quasar was also a fork. 

Such is the piracy life.

**Comment by scakemyer** [comment] 2019-02-07 06:29
Did I miss something?

**Closed as completed by scakemyer** 2019-02-07 06:29 UTC
