### ISSUE TITLE
Stream windows no video playback version 0.9.12

### ISSUE THREAD

**Issue by lcaleixo** [scakemyer/plugin.video.quasar#163] opened 2016-02-11 15:49 UTC
When search for a content, nothing happens: Quasar doesn't play anything and, if I've previsously selected in the context menu to display the streams, the Streams window never shows up.

Windows 7 32-bit
Language: portuguese-brazil
kodi 15.2
quasar 0.9.12
PS: But if I change the language to English, work fine.

**Comment by lcaleixo** [comment] 2016-02-11 17:08
+msgctxt "#30228"
+msgid "Available streams for"
+msgstr "Fontes **disponíveis** para"

problem occurs even with special characters

+msgctxt "#30228"
+msgid "Available streams for"
+msgstr "Fontes **disponiveis** para"

changing the character works fine..
and the stream of choice appears

**Comment by scakemyer** [comment] 2016-02-11 17:17
Duplicate of #142

**Closed by scakemyer** 2016-02-11 17:17 UTC
