### ISSUE TITLE
Add another context menu entry to delete files along with torrents

### ISSUE THREAD

**Issue by fullmetal1** [scakemyer/plugin.video.quasar#423] opened 2016-03-20 23:10 UTC
Can we get an option to delete torrents from the queue, and also delete all files and directories associated with that torrent?

**Comment by scakemyer** [comment] 2016-03-21 01:48
You mean like another context menu entry below "Delete torrent" that would read "Delete torrent and files"? If so I think that would make sense. You could also disable "Keep files after playback" while having background handling enabled, which also deletes files in that case.

**Comment by ShlomiD83** [comment] 2016-03-21 04:35
maybe "delete all" also?

**Comment by fullmetal1** [comment] 2016-03-21 21:02
but then files are removed immediately after playback correct?

I was thinking more the use case of letting the torrents seed until you need room and then deleting the torrent and files associated with the torrent all at once. Either the context menu, or an checkbox that "deleting torrents also removes associated files"

**Comment by scakemyer** [comment] 2016-03-21 21:27
That checkbox is already there, it's the "Keep files after playback/download stops" which is still accurate because of the "download stops" part. Combined with having background handling enabled, it acts just like you're asking.

**Comment by guindous** [comment] 2016-03-28 12:24
As fullmetal1 said I use the function "Keep files after playback/download stops" because I keep seeding files until my htpc needs some extra hd space (Torrenting is all about sharing, isn't it?). Is a nice feature to delete not only the torrent but also all files associated. Upvoting!

**Comment by incredulity** [comment] 2016-04-06 21:13
> "Delete torrent and files"? 

Yes.

I use the option to Keep Files.   Adding that context menu option would simply removing incomplete downloads while removing torrents I no longer wish to be transferring.

**Comment by guindous** [comment] 2016-12-26 21:11
I didn't notice that #603 was a duplicate of this enhancement. Sorry for that.

**Closed** 2017-01-19 11:33 UTC
Labels: enhancement

**Comment by scakemyer** [comment] 2017-01-19 11:35
done in scakemyer/quasar@7db7735 for reference..
