### ISSUE TITLE
Navigation error: HTTP Error 500 Internal server error

### ISSUE THREAD

**Issue by jovendor** [scakemyer/plugin.video.quasar#174] opened 2016-02-12 18:23 UTC
Hello,
I Installed quasar 0.9.12 in OS X and I get: 

"Navigation error: HTTP Error 500 Internal server error"

I have erased all folders and files for both quasar and pulsar to start a new installation a couple of times with no good results. I followed the process of installation correctly! But do not know how to fix that error. Could you please help?

Thanks in advance

**Comment by scakemyer** [comment] 2016-02-12 18:25
Duplicate of #142

**Closed by scakemyer** 2016-02-12 18:25 UTC

**Comment by jovendor** [comment] 2016-02-12 18:52
@scakemeyer,
Thanks for your prompt answer... I went through the duplicates posted # 142, # 105, # 163, and # 75 and could not find the solution to the problem.
I cannot open any stream movie, tv show or others at all and I am not dealing with different languages such us Portuguese or Hebrew as the case of those posts.

I would like to get a more clear answer to this item, 
Much appreciated,
J.

**Comment by scakemyer** [comment] 2016-02-12 19:00
Then I'll need logs to be able to help, there's just no other answer otherwise.

**Comment by jovendor** [comment] 2016-02-12 19:30
Thanks scakemyer,
here is the log
[kodi.txt](https://github.com/scakemyer/plugin.video.quasar/files/128519/kodi.txt)

**Comment by scakemyer** [comment] 2016-02-12 20:16
The quasar daemon can't reach Kodi, so either remote control is disabled (make sure you followed the [installation instructions](https://github.com/scakemyer/plugin.video.quasar#installation)), your firewall is blocking requests between both or you have something else running on port 9090.

**Comment by jovendor** [comment] 2016-02-12 21:42
1st and second are good so now I will check ports and let you know

**Comment by scakemyer** [comment] 2016-02-13 01:26
You can't. Kodi is using 9090 for JSON-RPC and it's not configurable. Change the other thing using that port or use Kodi on a dedicated box.

**Comment by jovendor** [comment] 2016-02-13 14:56
ok I totally suspended other application using 9090 and started Quasar but I continue having same problem so there is something else...  Any other thoughts please?

**Comment by Jizar07** [comment] 2016-02-19 03:38
Fresh install!!!!

**Comment by jovendor** [comment] 2016-02-20 12:32
After doing different combinations I decide to change the JSON port configuration in advanced settings file as below and it worked...

<jsonrpc>
    <compactoutput>false</compactoutput>
    <tcpport>9999</tcpport>
</jsonrpc>

**Comment by scakemyer** [comment] 2016-02-20 17:16
The daemon is hardcoded with the default 9090 port number, you'll have issues down the line, more specifically with getting the providers, library functions and infolabels.

**Comment by hfmls** [comment] 2016-05-03 17:39
i am having the same problem...using openelec ip as dmz so i guess i don't have to open port.
remote services are on too....no idea what to do next.

**Comment by Githeo** [comment] 2016-11-13 16:06
Hi, same problem here. Could you please not hardcode the port and use a conf file or provide us a workaround? I'm with the last version of Quasar. By the way, great job!

**Comment by philwolstenholme** [comment] 2017-12-14 21:36
I know this is closed but I'm leaving a comment for people who use search.

Hyperion, an Ambilight clone uses Kodi's JSON-RPC API on port 9090 too, so if you're running Hyperion then Quasar will not function correctly. You can kill the Hyperion process though, after which Quasar should work okay.
