### ISSUE TITLE
Strange titles when i browse movies

### ISSUE THREAD

**Issue by Rocologo** [scakemyer/plugin.video.quasar#708] opened 2017-02-07 18:25 UTC
When I browse movies through Quasar > Most Popular or any other category the movie ttiles are unreadable. See screenshot.

LOG: 
http://pastebin.com/7FAMPsQd

## Expected Behavior
readable titles...

## Current Behavior
Most the titles are unreadable,
![image](https://cloud.githubusercontent.com/assets/1008133/22704729/01820556-ed69-11e6-9fce-1843efd81b46.png)

## Possible Solution
I have tried to uninstall kodi, remove the .kodi folder and then install kodi+quasar+burst again, but the titles are still unreadable.

## Steps to Reproduce (for bugs)

1. reproduceable on my computer everytime i try. 
2.
3.
4.

## Your Environment
* Version used: 15.2 on a Linux Mint 18.1 (x64)
* Hardware Intel NUC D54250

**Comment by scakemyer** [comment] 2017-02-07 18:30
Duplicate of #82 and #239, and Kodi 15 is no longer supported as the readme now states.

**Closed by scakemyer** 2017-02-07 18:30 UTC

**Comment by elgatito** [comment] 2017-02-07 18:43
If it is not even working, then maybe worth setting dependency
http://kodi.wiki/view/addon.xml#Dependency_versions

**Comment by Rocologo** [comment] 2017-02-07 19:06
Problem was solved after upgrade to16.1

using the guide

sudo apt-get install software-properties-common
sudo add-apt-repository ppa:team-xbmc/ppa
sudo apt-get update
sudo apt-get install kodi

**Comment by scakemyer** [comment] 2017-02-07 19:07
@elgatito I've been meaning to update that and was leaving a little "grace" period before updating the dependency version, but thanks for the reminder.
