### ISSUE TITLE
Multi-files torrent support by plugin URL

### ISSUE THREAD

**Issue by TheWizIL** [scakemyer/plugin.video.quasar#36] opened 2016-01-31 20:46 UTC
Hello.

It will be great if we could play torrent file directly with index file in torrent.
Like: plugin://plugin.video.quasar?url=http://aa.com/aa.torrent&index=10
So this link will get url torrent and play file index 10 as show in torrent file structure.

I saw it working on script.module.torrent2http (https://github.com/DiMartinoXBMC/script.module.torrent2http)

Good day.

**Comment by scakemyer** [comment] 2016-01-31 20:55
Duplicate of #17, except maybe the index in url

**Comment by i96751414** [comment] 2016-01-31 21:01
The index thing is a great idea. I will work on this later

**Comment by scakemyer** [comment] 2016-02-01 01:04
Implemented in scakemyer/quasar#9 by @i96751414

**Closed by scakemyer** 2016-02-01 01:04 UTC
