### ISSUE TITLE
ERROR: [plugin.video.quasar] UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 3: ordinal not in range(128)

### ISSUE THREAD

**Issue by Sjodda** [scakemyer/plugin.video.quasar#240] opened 2016-02-17 20:20 UTC
```
20:41:53 T:139683555895168  NOTICE: Starting Kodi (15.2 Git:02e7013). Platform: Linux x86 64-bit
20:41:53 T:139683555895168  NOTICE: Using Release Kodi x64 build
20:41:53 T:139683555895168  NOTICE: Kodi compiled Jan 24 2016 by GCC 4.9.3 for Linux x86 64-bit version 4.1.16 (262416)
20:41:53 T:139683555895168  NOTICE: Running on OpenELEC (official) - Version: 6.0.1, kernel: Linux x86 64-bit version 4.1.16
20:41:53 T:139683555895168  NOTICE: FFmpeg version: 2.6.4
20:41:53 T:139683555895168  NOTICE: WARNING: unsupported ffmpeg version detected
20:41:53 T:139683555895168  NOTICE: Host CPU: Intel(R) Atom(TM) CPU 330 @ 1.60GHz, 4 cores available


20:42:03 T:139681949783808  NOTICE: [plugin.video.quasar] Updating quasar daemon...
20:42:04 T:139681949783808   ERROR: [plugin.video.quasar] Traceback (most recent call last):
20:42:04 T:139681949783808   ERROR: [plugin.video.quasar]   File "/storage/.kodi/addons/plugin.video.quasar/resources/site-packages/quasar/daemon.py", line 141, in quasard_thread
20:42:04 T:139681949783808   ERROR: [plugin.video.quasar]     proc = start_quasard(stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
20:42:04 T:139681949783808   ERROR: [plugin.video.quasar]   File "/storage/.kodi/addons/plugin.video.quasar/resources/site-packages/quasar/daemon.py", line 101, in start_quasard
20:42:04 T:139681949783808   ERROR: [plugin.video.quasar]     quasar_dir, quasar_binary = get_quasar_binary()
20:42:04 T:139681949783808   ERROR: [plugin.video.quasar]   File "/storage/.kodi/addons/plugin.video.quasar/resources/site-packages/quasar/daemon.py", line 70, in get_quasar_binary
20:42:04 T:139681949783808   ERROR: [plugin.video.quasar]     shutil.rmtree(dest_binary_dir)
20:42:04 T:139681949783808   ERROR: [plugin.video.quasar]   File "/home/stephan/projects/openelec-6.0/build.OpenELEC-Nvidia_Legacy.x86_64-6.0.1/Python-2.7.3/.install_pkg/usr/lib/python2.7/shutil.py", line 239, in rmtree
20:42:04 T:139681949783808   ERROR: [plugin.video.quasar]   File "/home/stephan/projects/openelec-6.0/build.OpenELEC-Nvidia_Legacy.x86_64-6.0.1/Python-2.7.3/.install_pkg/usr/lib/python2.7/posixpath.py", line 71, in join
20:42:04 T:139681949783808   ERROR: [plugin.video.quasar] UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 3: ordinal not in range(128)
20:42:04 T:139681949783808   ERROR: [plugin.video.quasar]
20:42:04 T:139681983354624  NOTICE: Thread FileCache start, auto delete: false
20:42:04 T:139681949783808   ERROR: Exception in thread Thread-2:
                                            Traceback (most recent call last):
                                              File "/home/stephan/projects/openelec-6.0/build.OpenELEC-Nvidia_Legacy.x86_64-6.0.1/Python-2.7.3/.install_pkg/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
                                              File "/home/stephan/projects/openelec-6.0/build.OpenELEC-Nvidia_Legacy.x86_64-6.0.1/Python-2.7.3/.install_pkg/usr/lib/python2.7/threading.py", line 504, in run
                                              File "/storage/.kodi/addons/plugin.video.quasar/resources/site-packages/quasar/daemon.py", line 141, in quasard_thread
                                                proc = start_quasard(stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
                                              File "/storage/.kodi/addons/plugin.video.quasar/resources/site-packages/quasar/daemon.py", line 101, in start_quasard
                                                quasar_dir, quasar_binary = get_quasar_binary()
                                              File "/storage/.kodi/addons/plugin.video.quasar/resources/site-packages/quasar/daemon.py", line 70, in get_quasar_binary
                                                shutil.rmtree(dest_binary_dir)
                                              File "/home/stephan/projects/openelec-6.0/build.OpenELEC-Nvidia_Legacy.x86_64-6.0.1/Python-2.7.3/.install_pkg/usr/lib/python2.7/shutil.py", line 239, in rmtree
                                              File "/home/stephan/projects/openelec-6.0/build.OpenELEC-Nvidia_Legacy.x86_64-6.0.1/Python-2.7.3/.install_pkg/usr/lib/python2.7/posixpath.py", line 71, in join
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 3: ordinal not in range(128)
```

**Comment by scakemyer** [comment] 2016-02-18 02:59
Duplicate of #210

**Closed by scakemyer** 2016-02-18 02:59 UTC
