### ISSUE TITLE
Speed very slow on buffering for Android ARM

### ISSUE THREAD

**Issue by Rikitik** [scakemyer/plugin.video.quasar#131] opened 2016-02-10 10:44 UTC
I'm having performance issues, my old android device used to be done with buffering in 1-3 Minutes (To build up peer connections/speed in Pulsar) Quasar  takes litterly 5-10 minutes to gain any speed if it doesn't just freeze up.. first 3 Minutes it stays at 0-1 KB than it sometimes speeds up to 50KB then drops again to 0-2 KB Torrent has 900+seeders and 100+ peers

Specs android 4.2.2 ARMv7(RK3288)
Wireless 300N (80Mbps=10 MB) Verified
MicroSD UHS-1 (40MB write 60MB read) Verified
HDD USB3.0 (25MB read/write USB 2.0 limitation)

Few other performance related issues,maybe background downloading should be disabled by default on Low performance systems(ARM ATOM)

**Comment by scakemyer** [comment] 2016-02-10 11:18
Background downloading doesn't change anything to performance, it's always been doing just that but would stop if you sneezed or touched anything. Check the connections limit and upload rate, since the whole stack is a lot faster and libtorrent is probably just overwhelming your router / internet connection now that it can, whereas it was just slow enough not to do so in earlier version. Your USB 2.0 connection might also be causing problems here, try internal storage with a smaller file to see if it makes any difference.

**Comment by Rikitik** [comment] 2016-02-10 11:49
Tried all, your suggestion before posting my router is High performance  and only 1.5 year old, so i doubt that. i like to request the option to set how many torrents start in the background, for my slow devices. Disabling background handling improved performance greatly. Still speed issues with buffering i get 300KB for 10 seconds then drops to 0-2 KB connection limited to 200

**Comment by compyy** [comment] 2016-02-10 11:59
This issue is already discussed here, its SD card issue.

http://forum.kodi.tv/showthread.php?tid=257967&pid=2240013#pid2240013

**Comment by Rikitik** [comment] 2016-02-10 12:08
I switched over to USB HDD, but it could be related to the dump files i guess

**Comment by scakemyer** [comment] 2016-02-10 13:38
The fast resume files don't slow down anything, it's your USB. There's nothing we can do about that, sorry.

**Comment by inkubux** [comment] 2016-02-10 19:45
I also suffer from the same issue on my Nvidia Shield. 
I don't have a an usb3 key at the moment to test if it would resolve the issue. 
Is the problem fixed with an USB key/HDD rather than an SD card ?

**Comment by Rikitik** [comment] 2016-02-10 23:05
I also do not think it is a hardware Issue since it worked perfect with pulsar before, but i can no argue with the developer. It isn't fast resume btw any streams slows down after about 10 seconds never surpossing 300KB for long. I'm sure it can handle 5MB/s atleast.

**Comment by scakemyer** [comment] 2016-02-10 23:44
The issue is that you're using a USB 2.0 HDD, that's all there is to it. Maybe the updated libtorrent is pickier about it, maybe your HDD is starting to fail, maybe both. But insisting on saying there's an issue when you're not even trying with internal storage and reporting if it helps isn't solving anything. You're welcome to go back to using Pulsar if it worked well for you.

**Closed by scakemyer** 2016-02-10 23:44 UTC

**Comment by Rikitik** [comment] 2016-02-11 12:21
No pulsar has provider issues, please do not be defencivei love the work you do, however i tried internal storage before comming here after that i tried MicroSD then HDD i retried internal as per your suggestion. in All instances it starts downloading the stream and the moment it reaches 200-300 it drops back to 0, i tried aditionally limiting connection to200 download upload speed to 2.5M/250KB respectivly This only seems to happen for android ARM Win 8 works fine

**Comment by inkubux** [comment] 2016-02-11 13:06
I do have the same issue with my MicroSD card and with the internal storage as well.

I'm just reporting it because I want to help. 

It starts buffering at around 200kb/s then drop to 2kb/s - 0kbp/s for about 3 minutes and then It starts buffering full speed (2mb/s and more) I have a 50mbps connection so i'm pretty confident it's not my network. My shield is wired and not wireless.

I hope it helps

**Comment by bongo264** [comment] 2017-03-29 00:35
I am not sure that it is a problem with SD or USB speeds. I have zetaTorrent running on the same box using the very same storage and it will regularly D/L at 1-2 Mbps. 
Otherwise I love it!!! 
Mostly I use it to queue up things to watch and just let them run in the background.

**Comment by scakemyer** [comment] 2017-03-31 18:44
Try enabling the "Tuned storage settings" in the BitTorrent section, if you have a little RAM to spare it might improve performance in your case.

**Comment by kamikasept** [comment] 2017-05-14 23:00
I have the same issue. I use a M9s pro with 3gb RAM. Sometimes it work fine bit the most of the time ir take seeds but the download dont pass above 1 ir 2kb/s

**Comment by compyy** [comment] 2017-05-18 09:41
I think issue should have been resolved with new version, i use internal storage for saving files so never had this issue again.
