### ISSUE TITLE
Ask about background handling when stopping stream

### ISSUE THREAD

**Issue by tstrul1** [scakemyer/plugin.video.quasar#281] opened 2016-02-21 11:38 UTC
Sometimes I try a specific stream and decide not to use it and try another one. Right now when I press stop the torrent is still downloading in background. I think it would be better to ask if I want to keep downloading the file if I press stop while the video is playing

**Comment by tomtomclub** [comment] 2016-02-21 11:45
You can remover the torrent

**Comment by tstrul1** [comment] 2016-02-21 11:47
Yes but I have to do it manually. And go back to the main menu.... Otherwise I will download two torrents at the same time if I choose another stream

**Comment by scakemyer** [comment] 2016-02-21 18:08
Pretty much a duplicate of #14, which once implemented will have the same effect with or without background handling.

**Closed by scakemyer** 2016-02-21 18:08 UTC
