### ISSUE TITLE
Automatically mark as "watched" after stream completion with library integration

### ISSUE THREAD

**Issue by Magic815** [scakemyer/plugin.video.quasar#16] opened 2016-01-30 05:09 UTC
Native Kodi won't automatically mark .strm's as "watched" after their completion. I've been told it has to do with Kodi treating .strm's as playlists and not videos.

However, I've also heard that addons themselves can force the action of marking the status as "watched" to get around Kodi's limitations.

I'd love to see code added to Quasar so that .strms can get automatically marked as watched after they get watched to completion.

---
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=30355803)](https://www.bountysource.com/issues/30355803-automatically-mark-as-watched-after-stream-completion-with-library-integration?utm_source=30355803&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by hfmls** [comment] 2016-01-30 12:00
Works with Genesis not pulsar,  it had to do with meta data I think.

**Comment by nix87** [comment] 2016-02-03 21:55
Genesis and Istream have that but again both addons are different from torrent streamnig addon I suppose. It would be nice to have that if it's possible though.

**Comment by m4xc4v413r4** [comment] 2016-02-10 11:29
Mine mark as watched, unless you're talking about when you watch through library integration. In this case it doesn't mark as watched neither does it call the trakt plugin to mark it watched and vote on trakt.

**Comment by nix87** [comment] 2016-02-12 23:01
Yes in library don't in addon itself he doing marking and not just marking e.g. if you watch 10% of movie he will mark that.

**Comment by hfmls** [comment] 2016-02-13 14:35
hi there, i think scrobble with trakt is working ok, but "marked" on library isn't?

**Comment by m4xc4v413r4** [comment] 2016-02-13 14:39
For me, trakt syncs if I watch something going to quasar lists, but if I
add something from the list to the library and watch it from the library,
it won't sync.

**Comment by hfmls** [comment] 2016-02-14 03:35
actually that happened to me with pulsar, but with QUASAR it's working ok, trakt scrobble.
only library "mark as watched" isn't.

**Comment by nix87** [comment] 2016-02-16 05:57
It would be nice feature but honestly it's not necessary at least in my point of view. I'm not trying to say don't do it. If developers won't bother and if it's not hard to implement that then yeah why not. It's just I'm not badly lazy like that I can't click marked as watched on my own xD

**Comment by scakemyer** [comment] 2016-02-16 06:02
Yeah it's not really a priority, lazy bastards can keep asking ;) Pushing the milestone a bit but it'd still be nice to have this sorted out before 1.0

**Comment by Magic815** [comment] 2016-02-16 13:01
+1 to the lazy bastard club, then. :) 

While I agree it's minor, now that we have integration of strms and local media in one library,  it's a disjointed experience for half of them to get auto flagged and the other half not.

If implemented, I would look to see what Kodi uses as a benchmark for the autoflagging. I've heard it does it at 90% file completion, but you might want to double check. I imagine you'd want Quasar to do it at the same percentage.

**Comment by hfmls** [comment] 2016-02-16 22:13
the thing is, after watching like 10 episodes of tv show and fall asleep sometimes i wake up and can't remember wich ones i've seen, but yeah it's not a big of deal, but it would be cool.
thank you in advance.

**Comment by scakemyer** [comment] 2016-02-16 22:25
That's what you get for binge watching 10 episodes.

**Comment by Magic815** [comment] 2016-02-16 22:34
But is it _really_ binge watching if the auto-marking doesn't happen? (If a tree falls, but no one is there to hear it... )

:D

**Comment by scakemyer** [comment] 2016-02-16 23:12
Well, I guess there won't be any more binge watching for a little while since we can't use the MovieDB anymore...

**Comment by MrYaz** [comment] 2016-02-18 21:51
:+1:  to this feature request!

LOL on @hfmls comment about falling asleep during binge watching... sounds exactly like me as well!

**Comment by therealasole** [comment] 2016-03-16 15:18
+1.
Any news on this?

**Comment by hfmls** [comment] 2016-03-18 12:33
scrobble is working but marked as watched is still not implemented i guess.

**Comment by therealasole** [comment] 2016-03-18 13:09
Automatically marked as watched is not implemented, that's why I asked.

**Comment by m4xc4v413r4** [comment] 2016-03-18 16:34
I continue to not understand what you guys are talking about... when i watch something on quasar it gets marked as watched. And no, I'm not talking about trakt, but that is also working.

**Comment by seltun** [comment] 2016-03-18 16:38
They are talking about when opening a stream from the library (Library Integration, strm files) at the end of watching the video it does not get marked as watched in the library, pulsar had this problem too

**Comment by hfmls** [comment] 2016-03-18 17:42
yes, that, when using the library strm files.

**Comment by JoseFSilva** [comment] 2016-04-21 18:01
Dear @scakemyer,

This enhacement would be very welcome and is the default behaviour when playing local files, so this would make the quasar library more consistent and even better integrated aand it would make us lazy bums and fall asleepers above happier 

I hope it's not forgotten

**Comment by burekas7** [comment] 2016-12-25 21:30
Hi @scakemyer 

Is there any new about this issue?

Thanks for all the best your efforts here.

**Comment by meijin007** [comment] 2017-01-16 21:21
I think this issue can be closed. It seems to work out of the box

**Comment by scakemyer** [comment] 2017-01-20 22:50
@meijin007 with library integration?

**Comment by meijin007** [comment] 2017-01-21 05:18
No

**Comment by Avishay-a** [comment] 2017-01-29 09:40
As to version 0.9.60, Automatically mark as "watched" in library still doesn't work.

Thanks for all your hard and excellent work :)

**Comment by KillerJoeBR** [comment] 2017-02-11 00:23
I would like this!

**Comment by scakemyer** [comment] 2017-02-11 01:48
Everyone using library integration would, which is why there's a $50 bounty on this in case someone else gets it done before I have a chance to.

**Closed** 2017-02-14 00:00 UTC
Labels: enhancement

**Comment by scakemyer** [comment] 2017-02-14 05:20
Enjoy in v0.9.70 :)

**Comment by Avishay-a** [comment] 2017-04-04 08:59
Hi scakemyer,
I've installed fresh clean Kodi, latest 17.1 and using latest Quasar, version 0.9.76.
The feature of Automatically mark as "watched" in library intwgration still doesn't work.
Could you advise?

Thanks for all your hard and excellent work :)

**Comment by elgatito** [comment] 2017-04-04 10:24
Please, refer to #821 . Post log file there.

**Comment by scakemyer** [comment] 2017-04-04 12:02
@Avishay-a It's a regression in 0.9.75 ...
