### ISSUE TITLE
Client version whsich Quasar uses?

### ISSUE THREAD

**Issue by nix87** [scakemyer/plugin.video.quasar#57] opened 2016-02-03 15:50 UTC
It's not an issue it's more like question. I'm interesting which version of libtorrent Quasar uses? I'm asking this cause if we ever come to the point where we can use private trackers as providers with Quasar it could be vital obstacle to avoid. I think everything could be done sometime like options "keep seeding after watching or download" or "turn on/off DHT" cause all of that should be available with client itself. As I said eralier Torrenter have also option keep seeding after download so i want to belive it's possible for Quasar to have that also.

The only one thing can stop that idea is torrent client, but fortunately I was seraching and found that every private tracker allows using libtorrent (rtorrent) as bit torrent client. :) And most version supported are libtorrent 0.11.x, libtorrent 0.12.x, libtorrent 0.13.x there is other specific who could be allowed by most of privates like libtorrent 0.10.4

So i hope that Quasar use some of those 0.11.x - 0.13.x versions? :)

**Comment by scakemyer** [comment] 2016-02-03 17:38
Quasar is currently using libtorrent 1.0.8. And yes, "keep seeding after watching"' will eventually be implemented. Marking as duplicate of #38 since it mostly relates to private trackers.

**Closed** 2016-02-03 17:38 UTC
Labels: duplicate
