### ISSUE TITLE
Quasar stuck on finding 0/1 seeders

### ISSUE THREAD

**Issue by rridder** [scakemyer/plugin.video.quasar#450] opened 2016-04-01 14:53 UTC
I'm having problems with quasar .26 and above. .25 was working fine.
When loading a movie the list off available options is working fine but when you click one it stuck on finding without any seeders even tough in the finder window it shows lots of seeds.
Same happens when i try to open a torrent manualy. When downgrading to .25 it is working again.

here is my log:
http://pastebin.com/j46yEBnX

i have the same problem on rpi2 and wetek play.

**Comment by entr** [comment] 2016-04-01 20:51
See if clearing cache fixes it. Just open context menu > Add-on Settings > OK (save clears the cache) or Advanced > Clear cache.

Try if a torrent starts after that. Try at least 2 times after cache is cleared. On my linux laptop it usually works right after I clear the cache but on my ODROID it starts downloading on my second try. What I've noticed so far is that happens after Quasar crashes. Weird, I know.

**Comment by drake0101** [comment] 2016-04-05 09:35
I have the same issue. For example: Im choosing a torrent with 1000's of seeds, but Quasar is stuck on "Finding" and 0/-1 seeds. I have to restart Kodi once or twice, choose the same torrent and then it will work. I'll save the log next time it happens...

**Comment by KillerJoeBR** [comment] 2016-04-06 02:45
Sometimes i get this issue too. It's quite random. Try some torrents and the download won't start. Can't find any seeders and peers. Quit quasar, try other ones and then come back to the same torrent and it works fine.

**Comment by vitalyg149** [comment] 2016-04-09 21:54
The way I fix that issue on windows is reset firewall then launch quasar and add it firewall again. That seem to fix it, then it starts doing it again a few weeks later. Not sure what causes it. Other bit torrent software works fine.

**Comment by johnisburt** [comment] 2016-10-24 15:47
Hi I am having a very close issue to this and apologise if it shouldn't be here.
I can use this all night with no issue, and do not turn off my kodi box overnight but leave it on.
When i try to use it the next night it sticks on finding until it times out. I restart kodi and back in business.
Im sorry i dont have any logs as its an android kodi box. (pulsar didnt ever do this)

**Comment by syagev** [comment] 2016-12-16 16:30
Had the exact same problem. For me, changing the library path in the addon's configuration resolved the issue

**Comment by scakemyer** [comment] 2017-01-04 08:10
Should all be fixed in v0.9.49, will reopen if not.

**Closed by scakemyer** 2017-01-04 08:10 UTC
Labels: daemon

**Comment by dawax70** [comment] 2017-01-06 15:31
Had also the same problem with 0.9.49
finding source 0/-1 seeds
On openelec - Rpi2

**Comment by delta-heavy** [comment] 2017-01-06 15:42
I'm also seeing -1 for peers(or leechers?) on a Win10 machine but it's able to download. In fact 0.9.49 fixed Quasar on that machine as it had stopped downloading altogether (-1/-1 for seed/peer) after some of the previous updates. Haven't experienced hangs on finding peers since 0.9.49 - fingers crossed.

**Comment by scakemyer** [comment] 2017-01-06 17:55
Please, logs or it didn't happen.

**Comment by krde** [comment] 2017-01-23 21:33
Having this same problem "finding source 0/-1 seeds" at least from 0.9.57 and above in Android and Windows (both with Jarvis 16.1)... but ... i found something if it helps you scakemyer... if i use the "clear cache" option from the EZ Cleaner add-on... then suddenly it works and finds hundreds of seeds... but... as soon as i exit and re-enter into Kodi... stops working again with "finding source 0/-1 seeds" but it doesn't work with other add-ons "clear cache" option... like merlin's one or addon installer's maintenance tool one... only works with the EZ Cleaner one as long as i stay into the Kodi running... but, as soon as i exit Kodi... stops working again.
At least with the 0.9.42 works fine all the time... no problem at all.
Seems like if Kodi mess up some cache/file or whatever related to Quasar when Kodi starts.
Let me know if you need me to send you anything to check whats going on with the new versions.

**Comment by scakemyer** [comment] 2017-01-23 23:47
The only cache files Quasar creates and uses are for directory listings and have absolutely nothing to do with torrents. As before the fix in 0.9.59, the worst that happens is stale Trakt lists or episode listings. So the issue is with something else in your systems.

**Comment by krde** [comment] 2017-01-24 14:07
Hey scakemyer... did you find something???? because you fixed my friend! you made it! at least on windows with the new 0.9.60 version... i will try it on android also... i've tried at least on Krypton and it works perfect with android, i was just trying with Krypton to check if it gets solved... and then i realized that you realeased a new 0.9.60 version and it works great... i will check it win Jarvis (actually the one i use) but i bet it will work perfect also... you must of been fixing something since the 0.9.58 until now because now it works perfect with the new versions.
Thanks! :)

**Comment by brunakov** [comment] 2017-08-27 08:36
Having the same problem . Here is my logfile: 
https://paste.ubuntu.com/25406402/ 
Any help would be much appreciated!
