### ISSUE TITLE
Quasar Crashes on Startup with Kodi 17 RC

### ISSUE THREAD

**Issue by ToniCipriani** [scakemyer/plugin.video.quasar#614] opened 2016-12-31 20:09 UTC
Quasar crashes on startup with Kodi 17 RC. Kodi was installed from the UWP Windows Store.

http://pastebin.com/y2KRkDuA

**Comment by scakemyer** [comment] 2016-12-31 20:34
Thanks, was looking into this while fixing the new libtorrent-go builds. Closing as a duplicate of #547 and #576, but could you uninstall and post a log of the installation instead?

**Closed by scakemyer** 2016-12-31 20:34 UTC
Labels: duplicate
