### ISSUE TITLE
Some characters in translations prevent dialogs and notifications from showing up

### ISSUE THREAD

**Issue by KillerJoeBR** [scakemyer/plugin.video.quasar#142] opened 2016-02-10 17:53 UTC
Hi there,

I'm getting a lot of this "http error 500" while opening the movies sections (probably the same thing happens in the TV section)

If i try opening a new section like "Top Rated" or Next Page inside a list, i get this error. If i try again a few time it works and i get the movie list.

So i don't know if the error is just the server that is down/slow or if it is the plugin bad behaving.

Log: http://pastebin.com/hnjrxUCK

**Comment by ShlomiD83** [comment] 2016-02-10 17:57
tvshows is working fine the last time i checked.

**Comment by ShlomiD83** [comment] 2016-02-10 18:25
0.9.10 gave me an error also, but only when using hebrew language. in english it seemed to work fine.

**Comment by ShlomiD83** [comment] 2016-02-10 18:39
can confirm that in english quasar is working like a stallion, maybe u should consider leaving all the translations out of the addon, it only causes problems.

**Comment by scakemyer** [comment] 2016-02-10 23:53
Note to translators: Please be careful with the syntax in .po files. I simply can't catch every missing quote that causes this kind of issue. Leaving out translations is not something I'd consider at this point, that's like banning cars because there are accidents. They're also very useful and a lot of people need them to enjoy the things they like.

**Comment by KillerJoeBR** [comment] 2016-02-11 00:14
The problem (at least in the portuguese translation) seems to be only while using special letters (ç, ì, À, etc...) in window dialogs.

Cause special letters inside the settings doesn't seem to cause any problem. Anyway it's better not to use special letters anywhere.

**Comment by scakemyer** [comment] 2016-02-11 01:56
Special characters should be handled properly by Quasar, please don't replace them as it's not the right way to fix this issue, and would just make it harder to debug if there are no more characters causing the issue in the first place. It's better to take a little more time to find what is causing this and fix it properly, or at least implement the workaround in code instead of the translations themselves. I'm also adding a script to check for basic errors in the .po files.

**Comment by KillerJoeBR** [comment] 2016-02-11 02:09
Ok thanks. I thought we should avoid special characters because of your response in another thread:

////////////////////////////////////////////////////////////////////////////////////

 @lrrosa
lrrosa commented 3 hours ago

In the Portuguese (Brazil) translation I use the letter "ç" in msgctxt "#30208". But the popup message of "Quasar daemon started" is never shown. If I replace it with the letter "c", this popup works again.
--------------------------------------------------------------------
scakemyer commented 3 hours ago

Wrong / different character set, not something that can be fixed in Quasar.

////////////////////////////////////////////////////////////////////////////////////

**Comment by scakemyer** [comment] 2016-02-11 02:23
Just link with the issue # instead of pasting the whole thing, and that was before the other reports and developments, please don't extrapolate a fix from a previous comment that did not even imply anything about removing special characters.

**Comment by KillerJoeBR** [comment] 2016-02-11 02:49
Ok sorry, i admit that i'm new with this whole github thing and i don't know how to do things properly. And there's also the language barrier. Anyway i won't change the translation file for now (unless it's necessary).

I really appreciate all your work in this project. Thanks

**Comment by meijin007** [comment] 2016-02-11 05:23
Maybe we should add an git-ignored file about how to translate? 
BTW, it's better to use software for doing it (POEdit is the one I use).

**Comment by scakemyer** [comment] 2016-02-11 05:47
Yes translators should use POEdit or similar, but the script I just added will at least catch any syntax errors in .po files on pull requests.

**Comment by ShlomiD83** [comment] 2016-02-13 09:08
it's not special letters or characters, it's the translation itself. if you translate the line "available streams for" you wont see the streams dialog anymore. that also stands for translation of notifications, they wont pop up when translated.

**Comment by tomer953** [comment] 2016-02-13 09:53
I can confirm that the problem is with string id 30228 - "Available streams for". when I omit this one the choose stream dialog work just fine..

**Comment by KillerJoeBR** [comment] 2016-02-13 11:32
I translated the line "available streams for" without using special characters and it works fine in Portuguese (Brazil). Are you sure there is no special character? Maybe there is also issue with the length?

**Comment by ShlomiD83** [comment] 2016-02-13 11:33
there are no special characters in hebrew.

**Comment by KillerJoeBR** [comment] 2016-02-13 11:38
Ok i look the hebrew translation and it goes like this:

msgctxt "#30230"
msgid "Play / resume torrent"
msgstr "ניגון/המשך טורנט"

I don't know the name/type of these letters but they are not normal letters. So whatever they are, they cause issues.

**Comment by ShlomiD83** [comment] 2016-02-13 11:39
these are normal hebrew letters. are you talking about the "/"?

**Comment by KillerJoeBR** [comment] 2016-02-13 11:45
talking about the letters itself. Not standard keyboard letters. ABCDEFG.... 

If there is a translation for japanese using their letters (いすえかくくもねるりit will probably get an error too.

**Comment by tomer953** [comment] 2016-02-13 11:49
The whole idea in translation is NOT to use the standard ABC right? heh..
I think the whole thing is some unicode error, maybe decode the string with utf-8 will help.

b.t.w, here is the Hebrew ASCII Table: http://www.ascii-codes.com/cp862.html (128-154)

**Comment by KillerJoeBR** [comment] 2016-02-13 11:54
Not really. A lot of languages uses the traditional alphabet. Portuguese, spanish, french, italian, etc... Just the words are different. I don't know why special characters and different alphabet cause issues. I have no knowledge about coding etc. Just trying to help as much as i can ;-)

**Comment by tomer953** [comment] 2016-02-13 11:59
Much appreciated.
but In Kodi side - there are nothing wrong with translations that not using the "familiar" ABC letters...
and "even" japanese translation to skin and add-ons is working fine.
I guess that with Quasar the problem is a little more complicated, because the daemon is running in the background and has is own "logic", and causing the problem. (I know it's related, because only a restart to the daemon, after 'fixing' the translation - will make the problem disappear). As I said, with my exp with addons and translation, it's related to utf-8 encoding, let's wait for the devs reply and see.

**Comment by m4xc4v413r4** [comment] 2016-02-13 14:47
Special chars on the Portuguese (Portugal) translation don't give me any problems, and we use a lot of ç and ã.

**Comment by endlessterror** [comment] 2016-02-13 15:38
Confirming the presense of this issue on quasar >= 0.9.12 and with the Greek language. Issue appears under RPi OpenELEC 6.0.1 as well as under linux_x64 (same OE version).

**Comment by KillerJoeBR** [comment] 2016-02-13 15:50
m4xc4,

The problem with special chars is mostly only in this line:

msgctxt "#30228"
msgid "Available streams for"
msgstr "Streams disponiveis para"

In your language translation there isn't any special char in this line. So you are fine.

**Comment by m4xc4v413r4** [comment] 2016-02-13 16:20
Ok, good to know, have to take a couple of minutes today to put in the new
lines.

**Comment by meijin007** [comment] 2016-02-13 17:50
@KillerJoeBR I think all of Hebrew is "special char" fot Kodi...
anyway, if we only need to un-translate this line, maybe it is a partial sulotion until fixing the bug itself? @scakemyer and @ShlomiD83 what do you think?

**Comment by ShlomiD83** [comment] 2016-02-13 17:53
i think that some lines dont need translation at all, it sounds better in english.

**Comment by m4xc4v413r4** [comment] 2016-02-13 17:55
@ShlomiD83 that's a personal preference and since not everyone likes the
same things or has the same opinions, we should leave those outside
development.

**Comment by ShlomiD83** [comment] 2016-02-13 17:58
so we wait for the devs to solve the issue. this a temporary workaround and definitly not the right fix.

**Comment by scakemyer** [comment] 2016-02-13 20:27
Possible fix coming up in v0.9.15 in half an hour or so.

**Comment by tomer953** [comment] 2016-02-13 21:29
I knew it something related to the encoding in utf-8 :] will test tomorrow, many thanks!

**Comment by KillerJoeBR** [comment] 2016-02-13 22:32
Ok i tried the new version 0.9.15 and unfortunately it's still not working with special chars in the problematic line (available streams for).

There is also the line:

msgctxt "#30208"
msgid "Quasar daemon has started"

that if i use special chars the message doesn't appear. But this one is less problematic cause the plugin works fine without the message appearing. In my android box the daemon starts almost instantly so no big deal. But i prefer to see the message, so in my portuguese translation i avoid to use special char in this line too. Everywhere else it's seems fine to use.

**Comment by scakemyer** [comment] 2016-02-13 22:43
F***

**Comment by meijin007** [comment] 2016-02-14 05:39
:\ any new ideas?

**Comment by roee88** [comment] 2016-02-14 07:57
@scakemyer

Suggested fix:
1. Revert related changes back to 0.9.14 (in the current release even in English problems appear)
2. Never hide exceptions: bsjonrpc.connection sends back errors to the deamon, print them to log. Alternatively, modify bsjonrpc/connection.py and print the exceptions in dispatch_item_single (do not use _log as is because it doesn't work due to missing handler).
3. Here is the real fix, do not mix unicode and str types. Specifically in quasar/rpc.py/Dialog_Select_Large subject is unicode while the localized string is utf-8 so the following line will throw an exception:` "%s %s" % (GetLocalizedString(title), subject)`.
Just encode subject to utf-8 before. Here is a common utility function I usually use:

```
def to_utf8(text):
    if isinstance(text, unicode):
        return text.encode('utf-8')
    return text


```

**Comment by tomer953** [comment] 2016-02-14 14:53
I can confirm that the latest commit fixed the problem in Hebrew.
Thank you all.

**Comment by ShlomiD83** [comment] 2016-02-14 18:55
Tomer is correct, it's working great,,

**Comment by scakemyer** [comment] 2016-02-14 19:06
Good to know you guys can try things before a release, I'll keep that in mind ;)

**Comment by scakemyer** [comment] 2016-02-14 19:44
v0.9.17 is out, closing this fucker :fu:

**Closed by scakemyer** 2016-02-14 19:44 UTC
Labels: bug
