### ISSUE TITLE
Library integration for Trakt lists

### ISSUE THREAD

**Issue by barnoy** [scakemyer/plugin.video.quasar#455] opened 2016-04-05 17:59 UTC
Like this addon very much, my primer one.

Just wanted to check if I got it right, or am I missing something...I only can see my Trakt.tv watchlist and collection (movies and tv shows) but can't get them into the kodi library automatically only one by one...am I right or am I doing something wrong.

TIA

**Comment by nix87** [comment] 2016-04-05 21:51
I think you are right.

**Comment by kingdingaling83** [comment] 2016-04-06 13:13
i have the same issue i just want to import ALL my tract shows. 
at the moment you have to click one by one and select 'add to library'

i have about 50 shows :(

**Comment by barnoy** [comment] 2016-04-06 13:20
I tried the quasar list integration add on program, and it was ok with my movies list but the tv shows list only created the library in the quasar add on user data but the kodi library wasn't updated.

I don't know if I'm doing something wrong or is it a non finished solution since I couldn't find any help to solve this. 

The quasar is a great add on but without a full trakt integration it's kind of cripple (salts and exodus have a more complete integration)

**Comment by BTopbas** [comment] 2016-04-26 07:29
This is imported. Same is here. +1

**Comment by marcelmah** [comment] 2016-11-13 15:56
I would just like to be able to browse my OTHER Trakt list from within Quasar. The 'problem' I have with Trakt is that when I watch a show from a series, the whole series gets removed from my watchlist. This is fine for movies, but not series where you want to watch the other episodes / seasons as well.

I read somewhere this is by design, the fix is to use other lists, but those aren't accessible from within Quasar. So I don't (want) require it to import a list into the Kodi library, just able to view other lists.

**Comment by scakemyer** [comment] 2016-12-14 11:23
Duplicate of #398

**Closed by scakemyer** 2016-12-14 11:23 UTC
Labels: duplicate
