### ISSUE TITLE
Quasar start demon failed

### ISSUE THREAD

**Issue by drkharin** [scakemyer/plugin.video.quasar#286] opened 2016-02-21 17:10 UTC
19:16:33 T:140156979894016  NOTICE: [plugin.video.quasar] quasard: starting quasard
19:16:33 T:140157156042496  NOTICE: [plugin.video.quasar] quasar: starting jsonrpc service
19:16:34 T:140156979894016  NOTICE: [plugin.video.quasar] Deleting stale files set([])
19:16:35 T:140157483194112  NOTICE: script.tv.show.next.aired: ### starting data update
19:16:35 T:140156979894016  NOTICE: [plugin.video.quasar] /home/googa/.kodi/userdata/addon_data/plugin.video.quasar/bin/linux_x64/quasar: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/googa/.kodi/userdata/addon_data/plugin.video.quasar/bin/linux_x64/quasar)
19:16:35 T:140156979894016  NOTICE: [plugin.video.quasar] System information: linux_x64 3.19.0-50-generic
19:16:35 T:140156979894016  NOTICE: [plugin.video.quasar] Kodi build version: 16.0 Git:a5f3a99
19:16:35 T:140156979894016  NOTICE: [plugin.video.quasar] OS type: Linux
19:16:35 T:140156979894016  NOTICE: [plugin.video.quasar] uname: ('Linux', 'googa-System-Product-Name', '3.19.0-50-generic', '#56~14.04.1-Ubuntu SMP Thu Feb 4 11:25:43 UTC 2016', 'x86_64', 'x86_64')

**Comment by meijin007** [comment] 2016-02-21 17:18
try `sudo apt-get install libstdc++6`

**Comment by tomtomclub** [comment] 2016-02-21 17:49
Or sudo apt-get update

**Comment by scakemyer** [comment] 2016-02-21 18:03
Duplicate of #45, #127, #168 ;)

**Closed by scakemyer** 2016-02-21 18:03 UTC
