### ISSUE TITLE
Unable to get the "Choose stream" dialog to open

### ISSUE THREAD

**Issue by ofiryaish** [scakemyer/plugin.video.quasar#105] opened 2016-02-07 17:03 UTC
when i try to open the streams menu of a movie or an episode, it shows like it loading the menu streams, but unfortunately, it just stop the process. when letting the add-on to choose the stream automatically, it's run perfect.
the problem occurred when i updated from 9.6 to 9.8.

**Comment by scakemyer** [comment] 2016-02-08 12:42
Please share logs, I can't really help otherwise.

**Comment by i96751414** [comment] 2016-02-08 12:49
Also, what's your language? Please try the same with English language

**Comment by i96751414** [comment] 2016-02-08 12:54
@scakemyer can I make a new (pretty much similar) window for "Choose Stream"? Using a xml window will solve this problem, I think.

**Comment by johnnyslt** [comment] 2016-02-08 13:14
Can you make one for the "Opening stream" dialog ? :D

**Comment by meijin007** [comment] 2016-02-08 13:52
Probably the same as https://github.com/scakemyer/plugin.video.quasar/issues/106 . 
(By the opener name I can tell he speaks hebrew :P)

**Comment by ofiryaish** [comment] 2016-02-08 13:55
i changed the language to English, and now it's working  just fine. i had the Hebrew version if it's helping you to fix the problem. 
another annoying problem is that when opening a list of files in a torrent (such as episodes of a series),  the list is not sort by names, so it is a mass.

thank you for helping.

**Comment by i96751414** [comment] 2016-02-08 14:06
Yeah... It's an issue related to python encodings and stuff..

**Comment by scakemyer** [comment] 2016-02-08 16:55
i96751414 please do about the xml dialog :)

**Comment by meijin007** [comment] 2016-02-08 18:55
will it fix the issue that you can't get any notification ("Need to restart Kodi" etc.) when language is Hebrew?

**Comment by meijin007** [comment] 2016-02-09 19:18
@i96751414 any news?

**Comment by i96751414** [comment] 2016-02-10 02:05
I will do this tomorrow.. Don't worry

**Comment by KillerJoeBR** [comment] 2016-02-11 00:55
The translation for portuguese (brazil) is also causing this issue. The problem is with special letters (ç, é,ã, etc) in some window dialogs. But it works fine in other areas (like inside settings, context menu).

Anyway i can fix it by changing the problematic words, but sometimes there is not a similar word without using these special letters, but i could just write it wrong anyway but it kinda looks ugly. But if it works it's no big deal.

So my question is: Should i never use these special letters (and have some grammatically incorrect words) or i can use those EXCEPT in the few dialogs windows what it causes errors?

**Comment by i96751414** [comment] 2016-02-11 01:12
This is a problem I had a long time ago with the old Pulsar.. I will try to fix it, but don't know if it's possible.

**Comment by KillerJoeBR** [comment] 2016-02-11 01:50
i96751414, in the meantime...

Should i avoid these special letters everywhere? or just in the problematic ones?

**Comment by i96751414** [comment] 2016-02-11 02:22
I think they are problematic only on notifications (right corner notifications).. but for now we should avoid those characters everywhere

**Comment by scakemyer** [comment] 2016-02-11 02:24
No, avoiding those characters is not the proper solution, see #142

**Comment by i96751414** [comment] 2016-02-11 02:25
Sorry.. going to delete that part

**Comment by scakemyer** [comment] 2016-02-11 02:25
No worries, just saying :)

**Comment by scakemyer** [comment] 2016-02-11 02:27
Moving this to #142

**Closed by scakemyer** 2016-02-11 02:27 UTC
Labels: bug
